
version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/node:13.8.0"
    steps:
      - checkout
      - run: npm i
      - save_cache: 
            key: "npm_packages"
            paths: 
                -/src/node-modules
      - run: npm run lint
      
  test:
    docker:
      - image: "circleci/node:13.8.0"
    steps:
      - checkout
      - restore_cache: 
            key: "npm_packages"
      - run: npm i
      - run: npm run test
      
  analyse:
    docker:
      - image: "circleci/node:13.8.0"
    steps:
      - checkout
      - run: npm i
      - restore_cache: 
            key: "npm_packages"
      - run: npm audit  
      
workflows:
  welcome:
    jobs:
      - build
      - test:
            requires:
                - build
      - analyse:
            requires:
                - test
